### ISSUE TITLE
Demandlib usable?

### ISSUE THREAD

**Issue by ckaldemeyer** [oemof/demandlib#11]
Hi everybody,

is the demandlib fully usable and are you already building projects on it?

I am reading some papers about heat load modelling atm and might use it for our project, too. But so far the documentation still seems to be a bit sparse ;)

I presume it uses the BDEW logic to model different sectors (GHD, ...) and building types (EFH, MFH, ...)? Is this right? And is there any external document that documents the underlying logic?

Best
Cord

**Comment by birgits** [comment]
Hey, we used it in the smenos project and I think other projects used it, too. It contains the BDEW electrical standard load profiles for residential and commercial loads, the BGW (now BDEW) heat load profiles for residential and commercial loads and a step load profile approach for industrial loads.

I originally wrote the heat load profile part according to the following document:
https://www.eko-netz.de/files/eko-netz/download/3.5_standardlastprofile_bgw_information_lastprofile.pdf

I think Uwe and Caro rewrote it to confirm to the oemof coding rules and I am not sure if they changed anything then, because I think there have been some modifications to the profiles suggested by the BDEW. I never looked at them though, sorry.

**Comment by ckaldemeyer** [comment]
Thanks!

**Comment by ckaldemeyer** [comment]
Maybe @uvchik and @caro-rli can add something about the changes?

**Comment by simnh** [comment]
I think the heat demand profile ist pretty good, and should work. It might not be suitable though for 1 district heating system or a single household, as it is rather an approach to model the demand of multiple houses.(kind of a standard load profile that only makes sense when being applied to a sufficiently large 'region'. but @uvchik  and @birgits  should know more about the restrictions of the application.  

 I used a multiple linear regression model to model heat demand of district heating systems. That has been implemented in R, but I can provide you with the mathematical model. You need training data for this model of course..

New models for the feedinlib would also be great! ;)

**Comment by uvchik** [comment]
> But so far the documentation still seems to be a bit sparse  ;)

You cannot find all equations in the documentation.
http://demandlib.readthedocs.io/en/latest/api/demandlib.html#demandlib.bdew.HeatBuilding

You can find the link in the docstring.
http://demandlib.readthedocs.io/en/latest/api/demandlib.html#id1

**Comment by ckaldemeyer** [comment]
> You cannot find all equations in the documentation.
> http://demandlib.readthedocs.io/en/latest/api/demandlib.html#demandlib.bdew.HeatBuilding
> 
> You can find the link in the docstring.
> http://demandlib.readthedocs.io/en/latest/api/demandlib.html#id1
>  
>   
>             
>  
> Write

Nice. Thanks

**Comment by uvchik** [comment]
@ckaldemeyer : Shall we close this issue?

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer : Shall we close this issue?

I'll close it. Thanks!
